---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: authentik-secret
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: ca136c1b-4c64-413c-996a-b40b011642ff
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgresql
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: authentik-postgresql
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: 0ce4a200-5a0e-49dd-bcdf-b40b01167180
    - secretKey: postgres-password
      remoteRef:
        key: 0ce4a200-5a0e-49dd-bcdf-b40b01167180
