apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: 2026.2.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: secret_key
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-postgresql
              key: password

    postgresql:
      enabled: true
      auth:
        username: authentik
        database: authentik
        existingSecret: authentik-postgresql
        secretKeys:
          adminPasswordKey: postgres-password
          userPasswordKey: password
      primary:
        persistence:
          enabled: true
          storageClass: longhorn
          size: 8Gi

    server:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - auth.trashstack.dev
        tls:
          - hosts:
              - auth.trashstack.dev
            secretName: authentik-tls
