---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: nextcloud
    creationPolicy: Owner
  data:
    - secretKey: nextcloud-username
      remoteRef:
        key: 2cad2d13-1a74-4d48-b2a0-b40a0109d3a4
    - secretKey: nextcloud-password
      remoteRef:
        key: 2960b405-0cac-4a44-b4e8-b40a0109b436
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-postgresql
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: nextcloud-postgresql
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: e2ec8e68-fad0-4ed8-8c60-b40a0109f9d7
    - secretKey: postgres-password
      remoteRef:
        key: e2ec8e68-fad0-4ed8-8c60-b40a0109f9d7
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-redis
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: nextcloud-redis
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: e235028b-b9d8-4d55-a6eb-b40a010a0677
