apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 1h
  chart:
    spec:
      chart: nextcloud
      version: 9.0.5
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    image:
      tag: 33.0.2-apache
    nextcloud:
      host: cloud.trashstack.dev
      existingSecret:
        enabled: true
        secretName: nextcloud
      extraEnv:
        - name: OVERWRITEPROTOCOL
          value: https
        - name: OVERWRITEHOST
          value: cloud.trashstack.dev
        - name: overwrite.cli.url
          value: https://cloud.trashstack.dev
        - name: TRUSTED_PROXIES
          value: 5.9.57.177
        - name: APACHE_DISABLE_REWRITE_IP
          value: "1"
      phpConfigs:
        opcache.interned_strings_buffer: "10"

    internalDatabase:
      enabled: false

    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            existingSecret: nextcloud-postgresql
            secretKeys:
              adminPasswordKey: postgres-password
              userPasswordKey: password
      image:
        tag: 16.3.0-debian-12-r10
      primary:
        persistence:
          enabled: true
          storageClass: longhorn

    redis:
      enabled: true
      auth:
        existingSecret: nextcloud-redis
        existingSecretPasswordKey: redis-password
      replica:
        replicaCount: 0

    persistence:
      enabled: true
      storageClass: longhorn
      size: 50Gi

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.middlewares: nextcloud-nextcloud-chain@kubernetescrd
      tls:
        - hosts:
            - cloud.trashstack.dev
          secretName: nextcloud-tls

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
