apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sure-secret
  namespace: sure
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: sure-secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: 6707c9ee-83c8-4f53-8383-b412014e7c46
    - secretKey: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
      remoteRef:
        key: 0878632e-83c9-4933-81fd-b412014e7c96
    - secretKey: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
      remoteRef:
        key: 29e2a0c5-c33a-4e29-8fe9-b412014e7ce4
    - secretKey: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
      remoteRef:
        key: 555f5cce-2767-4ae4-a7b9-b412014e7d3f
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: f4e7b0b8-310d-4294-aecf-b412014e7e8d
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: ba671f7a-f17d-436a-8dfe-b412014e7edb
    - secretKey: redis-password
      remoteRef:
        key: 54fe8ecc-8f0d-4390-92e5-b412014e7deb
    - secretKey: db-username
      remoteRef:
        key: 331c25db-ff2d-4288-8937-b4130009749a
    - secretKey: db-password
      remoteRef:
        key: U8O54JPamlegAaXke79v0Ksc1XzEYrEsuBPkD8kt
