---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-discord-alerts
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: flux-discord-alerts
  data:
    - secretKey: address
      remoteRef:
        key: 7c82e9eb-0d26-4ac6-aaed-b40a015c2ac6
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-github-token
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: flux-github-token
  data:
    - secretKey: token
      remoteRef:
        key: 35788e95-c2d8-4136-9526-b40a015f446e
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-discord-audit
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: flux-discord-audit
  data:
    - secretKey: address
      remoteRef:
        key: 3d18ddb8-97cf-4494-877f-b40a015c61a9
