---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  releaseName: external-secrets
  timeout: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: external-secrets
      version: "0.x"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    bitwarden-sdk-server:
      enabled: true
